Page to post Info on beers
picasso-utc/vivaldi pull request #44
Opened 2022-10-10 17:02 UTC by geosaglio

Sa marche niquel
<img width="1440" alt="Screen Shot 2022-10-10 at 19 00 34" src="https://user-images.githubusercontent.com/52065610/194918441-5f33bc29-7d51-4d76-b366-38b82452e925.png">
<img width="1440" alt="Screen Shot 2022-10-10 at 19 01 55" src="https://user-images.githubusercontent.com/52065610/194918445-1b800624-806a-4e2f-b3b3-916e02f59291.png">
<img width="1440" alt="Screen Shot 2022-10-10 at 19 02 00" src="https://user-images.githubusercontent.com/52065610/194918449-89d94e69-9df0-49c2-8f94-04ab25414ab7.png">

2022-10-11 15:53 UTC, adrsimon commented on src/pages/Admin.js
> +				case asset_url("/admin/beerInfo"):
indentation

2022-10-11 15:59 UTC, maxime-vaillant requested changes

2022-10-11 15:59 UTC, maxime-vaillant commented on src/components/admin/application_management/BeerInfo.js
> +            setBeerInfo(infos);
```suggestion
            setBeerInfo(res.data);
```

2022-10-11 15:59 UTC, maxime-vaillant commented on src/components/admin/application_management/BeerInfo.js
> +            setBeerInfo(infos);
Pas besoin de déclarer une variable là

2022-10-11 15:59 UTC, maxime-vaillant commented on src/components/admin/application_management/BeerInfo.js
> +        console.log(beerInfo);
!

2022-10-11 15:59 UTC, maxime-vaillant commented on src/pages/Admin.js
> +				case asset_url("/admin/beerInfo"):
Indentation

2022-10-12 07:09 UTC, maxime-vaillant approved these changes

2022-10-12 14:26 UTC, geosaglio commented
J'ai fais un nouveaux commit, c'était juste pour que les bières s'affiche dans un ordre consistent.

2022-10-13 16:33 UTC, merged